# fly.toml app configuration file generated for ch-key on 2025-07-02T00:01:52+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ch-key'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 9292
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
